name: Blogspot archive update

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README Blogspot archive
    runs-on: ubuntu-latest
    steps:
      - name: Update Blogspot posts in README
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://zrsaimun.blogspot.com/rss.xml
          readme-section: posts
